### ISSUE TITLE
Stacks for v1 aren't accurate

### ISSUE THREAD

**Issue by ejizba** [pragnagopa/azure-functions-supported-runtime-stacks#5]
Right now it says "~1" works with Node.js v8, but that should be Node.js v6.

Also, there's no .NET Framework 4.7 listed at all. I'm not entirely sure how this would be added to the results because there's already a "dotnet" and the "display" is ".NET Core", not ".NET Framework".

Should I just skip using this API when listing v1 runtime stacks? If so - I would suggest you remove "~1" from Node.js v8 so that we're not in a weird half-accurate state.

**Comment by pragnagopa** [comment]
Fixed "SupportedRuntimeVersions" for node 8. 

For V1, please skip using this API.
