### ISSUE TITLE
Update stacks to include "custom" to support creating custom handlers

### ISSUE THREAD

**Issue by pragnagopa** [pragnagopa/azure-functions-supported-runtime-stacks#8]
cc @anthonychu @yojagad

@anthonychu - Ux relies on templates to create functions for given worker runtime. Should we hold off updating stacks until https://github.com/Azure/azure-functions-templates/issues/955 is fixed?

**Comment by pragnagopa** [comment]
@ammanifold / @shimedh -  This item is to track adding support to create function app for: [functions-custom-handlers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers)

- Worker runtime should be set to `Custom`
- Stack drop down will show `Custom`
- No version drop down. 

I will update the stacks for `Custom`. Ok to leave `runtimeVersion` property as null?

**Comment by ammanifold** [comment]
@pragnagopa sorry a few questions here. What is the ETA for this stack? Will it start as preview? What versions of functions runtime will support it?

**Comment by pragnagopa** [comment]
> sorry a few questions here

Any thing :) Do you need templates to be ready before we can show this option in portal?

> What is the ETA for this stack

Feature is in preview now. Yes, we would like to start supporting create flows while in preview. ETA for GA ~2-3months from now. 

> What versions of functions runtime will support it?

~2 and ~3

**Comment by pragnagopa** [comment]
@divyagandhii - CustomHandler apps will set `linuxFxVersion` to `custom`. Is this OK? Note no `|`

**Comment by pragnagopa** [comment]
Updating linuxFxVersion with `Custom` fails with error: `Message: "The parameter LinuxFxVersion has an invalid value."` . This is an Antares change. I will track this as part of ANT89

PR: https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/3123778 to allow `Custom`

**Comment by anthonychu** [comment]
I don’t think we need templates for the portal. Just a create experience that supports creating a function app that a custom handler app can be published to is fine.

I’m thinking maybe we want to call the stack “None” instead of “Custom”. This is because a custom handler app might want to use, for example, Python 3.7 and they should still use the existing LinuxFxVersion for that. However, in many cases, they don’t want a stack at all so they would choose “None”.

If we called it “Custom”, people might think they *must* use it if they are building any custom handler app, when they might actually need one of the existing stacks because of the type of app they’re building.

**Comment by pragnagopa** [comment]
Here is my take on this.  

Current design for stacks api is **Per Stack**.  For a given stack, this api provides AppSettings and SiteConfig properties. We should not be combining `Custom`  with existing stacks.  

- Runtimes and versions provided by the platform have deprecation policies.  Custom handlers do not have that restriction.
- Selecting Custom means that user is bringing in the the components needs to run the custom handler.  
-  If user chooses to use a runtime that is shipped as part of the platform, they can do it explicitly by setting the necessary config / appsettings by referring to the stacks info. We should not provide first class support for this from the tooling.


Let's sync up offline if we need to discuss more

**Comment by pragnagopa** [comment]
@anthonychu  - gentle ping on this. Supporting `custom` for linuxFxVersion needs Antares change and ANT89 deadline is coming up.

**Comment by anthonychu** [comment]
Got it. I think I understand it more now that I looked closely at the other stacks. Custom sounds fine to me, as long as the customer is still able to choose something like Python 3.7 and deploy a custom handler app to it. Thanks!
